// <auto-generated />
using System;
using Lone.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lone.Infrastructure.Persistencia.Migracoes
{
    [DbContext(typeof(LoneDbContext))]
    [Migration("20260925004941_CadastroEtiquetas")]
    partial class CadastroEtiquetas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("SeqPessoaCodigo");

            modelBuilder.Entity("Lone.Domain.Entidades.Bloqueio", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Escopo")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("FimEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("FimPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("InicioEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("InicioPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("MotivoLiberacao")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<byte>("Origem")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("PessoaId", "FimEm");

                    b.ToTable("PessoaBloqueios", (string)null);
                });

            modelBuilder.Entity("Lone.Domain.Entidades.CampoPersonalizado", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("CasasDecimais")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dica")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte>("Entidade")
                        .HasColumnType("tinyint");

                    b.Property<decimal?>("Maximo")
                        .HasPrecision(19, 6)
                        .HasColumnType("decimal(19,6)");

                    b.Property<decimal?>("Minimo")
                        .HasPrecision(19, 6)
                        .HasColumnType("decimal(19,6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<bool>("Obrigatorio")
                        .HasColumnType("bit");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<byte>("Tipo")
                        .HasColumnType("tinyint");

                    b.Property<byte[]>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Entidade", "Nome")
                        .IsUnique();

                    b.HasIndex("Entidade", "Ativo", "Ordem");

                    b.ToTable("CamposPersonalizados", (string)null);
                });

            modelBuilder.Entity("Lone.Domain.Entidades.CampoPersonalizadoOpcao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CampoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("CampoId", "Ordem");

                    b.ToTable("CampoPersonalizadoOpcoes", (string)null);
                });

            modelBuilder.Entity("Lone.Domain.Entidades.ContaCliente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("CondicaoPagamento")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DescontoMaximo")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("DiasMaximoAtraso")
                        .HasColumnType("int");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ExigeAprovacaoAcimaLimite")
                        .HasColumnType("bit");

                    b.Property<decimal?>("LimiteCredito")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("VendedorPadraoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("VendedorPadraoId");

                    b.HasIndex("PessoaId", "EmpresaId")
                        .IsUnique();

                    b.ToTable("ContasCliente", (string)null);
                });

            modelBuilder.Entity("Lone.Domain.Entidades.ContaFornecedor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("Avaliacao")
                        .HasColumnType("tinyint");

                    b.Property<string>("CondicaoPagamento")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("LeadTimeDias")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("PrazoMedioDias")
                        .HasColumnType("int");

                    b.Property<Guid?>("TransportadoraPadraoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("TransportadoraPadraoId");

                    b.HasIndex("PessoaId", "EmpresaId")
                        .IsUnique();

                    b.ToTable("ContasFornecedor", (string)null);
                });

            modelBuilder.Entity("Lone.Domain.Entidades.Contato", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Cargo")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Celular")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("CelularWhatsApp")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Departamento")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PessoaVinculadaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Principal")
                        .HasColumnType("bit");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Celular");

                    b.HasIndex("Email");

                    b.HasIndex("PessoaId");

                    b.HasIndex("PessoaVinculadaId");

                    b.HasIndex("Telefone");

                    b.ToTable("PessoaContatos", (string)null);
                });

            modelBuilder.Entity("Lone.Domain.Entidades.Estabelecimento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("CnaePrincipal")
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("char(7)")
                        .IsFixedLength();

                    b.Property<string>("CnaesSecundarios")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("char(14)")
                        .IsFixedLength();

                    b.Property<DateTime?>("ConsultadoReceitaEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EnderecoFiscalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("IndicadorIE")
                        .HasColumnType("tinyint");

                    b.Property<string>("InscricaoEstadual")
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("varchar(14)");

                    b.Property<string>("InscricaoMunicipal")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("InscricaoSuframa")
                        .HasMaxLength(9)
                        .IsUnicode(false)
                        .HasColumnType("varchar(9)");

                    b.Property<string>("NaturezaJuridica")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Principal")
                        .HasColumnType("bit");

                    b.Property<byte>("RegimeTributario")
                        .HasColumnType("tinyint");

                    b.Property<string>("SituacaoReceita")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasFilter("[Cnpj] IS NOT NULL");

                    b.HasIndex("EnderecoFiscalId");

                    b.HasIndex("PessoaId");

                    b.ToTable("Estabelecimentos", (string)null);
                });

            modelBuilder.Entity("Lone.Domain.Entidades.Etiqueta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .UseCollation("Latin1_General_CI_AI");

                    b.Property<byte[]>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Etiquetas", (string)null);
                });

            modelBuilder.Entity("Lone.Domain.Entidades.GrupoEconomico", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte[]>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("GruposEconomicos", (string)null);
                });

            modelBuilder.Entity("Lone.Domain.Entidades.MeioContato", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("PermiteComunicacao")
                        .HasColumnType("bit");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Principal")
                        .HasColumnType("bit");

                    b.Property<byte>("Tipo")
                        .HasColumnType("tinyint");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.HasIndex("Valor");

                    b.ToTable("PessoaMeiosContato", (string)null);
                });

            modelBuilder.Entity("Lone.Domain.Entidades.Municipio", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<byte>("CodigoUf")
                        .HasColumnType("tinyint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("NomeBusca")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("NomeBusca");

                    b.HasIndex("Uf", "NomeBusca");

                    b.ToTable("Municipios", (string)null);
                });

            modelBuilder.Entity("Lone.Domain.Entidades.PendenciaMunicipio", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoIbgeOriginal")
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("varchar(7)");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MunicipioId")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte>("Origem")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RegistroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ResolvidaEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResolvidaPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TextoOriginal")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UfOriginal")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("MunicipioId");

                    b.HasIndex("ResolvidaEm");

                    b.HasIndex("PessoaId", "ResolvidaEm");

                    b.ToTable("PendenciasMunicipio", (string)null);
                });

            modelBuilder.Entity("Lone.Domain.Entidades.Perfil", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Administrador")
                        .HasColumnType("bit");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<byte[]>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Perfis", (string)null);
                });

            modelBuilder.Entity("Lone.Domain.Entidades.PerfilPermissao", b =>
                {
                    b.Property<Guid>("PerfilId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.HasKey("PerfilId", "Codigo");

                    b.ToTable("PerfilPermissoes", (string)null);
                });

            modelBuilder.Entity("Lone.Domain.Entidades.Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apelido")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("CapitalSocial")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR SeqPessoaCodigo");

                    b.Property<byte>("CorRaca")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("DataAbertura")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("DocumentoPrincipal")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<byte>("Escolaridade")
                        .HasColumnType("tinyint");

                    b.Property<byte>("EstadoCivil")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("GrupoEconomicoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("IdentidadeGenero")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("MescladaEmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nacionalidade")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int?>("NaturalidadeMunicipioId")
                        .HasColumnType("int");

                    b.Property<byte>("Natureza")
                        .HasColumnType("tinyint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NomeExibicao")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("NomeMae")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NomePai")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NomeSocial")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("OrigemCadastro")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Porte")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateOnly?>("PrimeiroContatoEm")
                        .HasColumnType("date");

                    b.Property<string>("Profissao")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<byte>("Sexo")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Situacao")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("SituacaoAlteradaEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("SituacaoMotivo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("DataNascimento");

                    b.HasIndex("GrupoEconomicoId");

                    b.HasIndex("MescladaEmId");

                    b.HasIndex("NaturalidadeMunicipioId");

                    b.HasIndex("Nome");

                    b.HasIndex("Situacao");

                    b.HasIndex("Natureza", "DocumentoPrincipal")
                        .IsUnique()
                        .HasFilter("[DocumentoPrincipal] IS NOT NULL AND [Natureza] <> 2");

                    b.ToTable("Pessoas", (string)null);
                });

            modelBuilder.Entity("Lone.Domain.Entidades.PessoaConsentimento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Canal")
                        .HasColumnType("tinyint");

                    b.Property<bool>("Concedido")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ConcedidoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Origem")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RevogadoEm")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId", "Canal")
                        .IsUnique();

                    b.ToTable("PessoaConsentimentos", (string)null);
                });

            modelBuilder.Entity("Lone.Domain.Entidades.PessoaDocumento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("EmitidoEm")
                        .HasColumnType("date");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("OrgaoEmissor")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Tipo")
                        .HasColumnType("tinyint");

                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<DateOnly?>("ValidoAte")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.ToTable("PessoaDocumentos", (string)null);
                });

            modelBuilder.Entity("Lone.Domain.Entidades.PessoaEndereco", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Bairro")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Cep")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("CodigoMunicipioIbge")
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("char(7)")
                        .IsFixedLength();

                    b.Property<string>("CodigoPais")
                        .IsRequired()
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("Complemento")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<short>("Finalidades")
                        .HasColumnType("smallint");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("MunicipioId")
                        .HasColumnType("int");

                    b.Property<string>("Numero")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("MunicipioId");

                    b.HasIndex("PessoaId", "Ordem");

                    b.ToTable("PessoaEnderecos", (string)null);
                });

            modelBuilder.Entity("Lone.Domain.Entidades.PessoaEtiqueta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EtiquetaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Texto")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("EtiquetaId", "PessoaId");

                    b.HasIndex("PessoaId", "EtiquetaId")
                        .IsUnique();

                    b.ToTable("PessoaEtiquetas", (string)null);
                });

            modelBuilder.Entity("Lone.Domain.Entidades.PessoaPapel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("FimEm")
                        .HasColumnType("date");

                    b.Property<DateOnly>("InicioEm")
                        .HasColumnType("date");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte>("Papel")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Papel", "Ativo");

                    b.HasIndex("PessoaId", "Papel")
                        .IsUnique();

                    b.ToTable("PessoaPapeis", (string)null);
                });

            modelBuilder.Entity("Lone.Domain.Entidades.PessoaRelacionamento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("FimEm")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("InicioEm")
                        .HasColumnType("date");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("PessoaDestinoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TipoRelacionamentoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PessoaDestinoId");

                    b.HasIndex("PessoaId");

                    b.HasIndex("TipoRelacionamentoId");

                    b.ToTable("PessoaRelacionamentos", (string)null);
                });

            modelBuilder.Entity("Lone.Domain.Entidades.PessoaSocio", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Documento")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateOnly?>("EntradaEm")
                        .HasColumnType("date");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Qualificacao")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.ToTable("PessoaSocios", (string)null);
                });

            modelBuilder.Entity("Lone.Domain.Entidades.PessoaValorPersonalizado", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CampoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("OpcaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ValorData")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("ValorLogico")
                        .HasColumnType("bit");

                    b.Property<decimal?>("ValorNumero")
                        .HasPrecision(19, 6)
                        .HasColumnType("decimal(19,6)");

                    b.Property<string>("ValorTexto")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("OpcaoId");

                    b.HasIndex("CampoId", "OpcaoId");

                    b.HasIndex("CampoId", "ValorData");

                    b.HasIndex("CampoId", "ValorNumero");

                    b.HasIndex("PessoaId", "CampoId")
                        .IsUnique();

                    b.ToTable("PessoaValoresPersonalizados", (string)null);
                });

            modelBuilder.Entity("Lone.Domain.Entidades.RegistroAuditoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<byte>("Acao")
                        .HasColumnType("tinyint");

                    b.Property<string>("Campo")
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.Property<Guid>("OperacaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Origem")
                        .HasColumnType("tinyint");

                    b.Property<string>("RaizEntidade")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.Property<Guid?>("RaizId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RegistroId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ValorAnterior")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ValorNovo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("OperacaoId");

                    b.HasIndex("Entidade", "RegistroId");

                    b.HasIndex("RaizEntidade", "RaizId", "DataHora");

                    b.ToTable("Auditoria", (string)null);
                });

            modelBuilder.Entity("Lone.Domain.Entidades.TipoRelacionamento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("NomeInverso")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<bool>("Sistema")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("TiposRelacionamento", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5a0e6f10-0000-0000-0000-000000000001"),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Sócio de",
                            NomeInverso = "Tem como sócio",
                            Sistema = true
                        },
                        new
                        {
                            Id = new Guid("5a0e6f10-0000-0000-0000-000000000002"),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Responsável por",
                            NomeInverso = "Tem como responsável",
                            Sistema = true
                        },
                        new
                        {
                            Id = new Guid("5a0e6f10-0000-0000-0000-000000000003"),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Representante de",
                            NomeInverso = "Representada por",
                            Sistema = true
                        },
                        new
                        {
                            Id = new Guid("5a0e6f10-0000-0000-0000-000000000004"),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Contato de",
                            NomeInverso = "Tem como contato",
                            Sistema = true
                        },
                        new
                        {
                            Id = new Guid("5a0e6f10-0000-0000-0000-000000000005"),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Dependente de",
                            NomeInverso = "Tem como dependente",
                            Sistema = true
                        },
                        new
                        {
                            Id = new Guid("5a0e6f10-0000-0000-0000-000000000006"),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Funcionário de",
                            NomeInverso = "Tem como funcionário",
                            Sistema = true
                        });
                });

            modelBuilder.Entity("Lone.Domain.Entidades.TokenRenovacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dispositivo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("EstabelecimentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(44)
                        .IsUnicode(false)
                        .HasColumnType("varchar(44)");

                    b.Property<DateTime?>("RevogadoEm")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SubstituidoPorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.HasIndex("UsuarioId", "RevogadoEm");

                    b.ToTable("TokensRenovacao", (string)null);
                });

            modelBuilder.Entity("Lone.Domain.Entidades.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DeveTrocarSenha")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<byte[]>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Lone.Domain.Entidades.UsuarioAcesso", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("BloqueadoAte")
                        .HasColumnType("datetime2");

                    b.Property<int>("TentativasFalhas")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimoAcessoEm")
                        .HasColumnType("datetime2");

                    b.HasKey("UsuarioId");

                    b.ToTable("UsuarioAcessos", (string)null);
                });

            modelBuilder.Entity("Lone.Domain.Entidades.UsuarioPerfil", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PerfilId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("PerfilId");

                    b.HasIndex("UsuarioId", "PerfilId", "EmpresaId")
                        .IsUnique();

                    b.ToTable("UsuarioPerfis", (string)null);
                });

            modelBuilder.Entity("Lone.Domain.Entidades.Bloqueio", b =>
                {
                    b.HasOne("Lone.Domain.Entidades.Pessoa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Lone.Domain.Entidades.Pessoa", null)
                        .WithMany("Bloqueios")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lone.Domain.Entidades.CampoPersonalizadoOpcao", b =>
                {
                    b.HasOne("Lone.Domain.Entidades.CampoPersonalizado", null)
                        .WithMany("Opcoes")
                        .HasForeignKey("CampoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lone.Domain.Entidades.ContaCliente", b =>
                {
                    b.HasOne("Lone.Domain.Entidades.Pessoa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Lone.Domain.Entidades.Pessoa", null)
                        .WithMany("ContasCliente")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lone.Domain.Entidades.Pessoa", null)
                        .WithMany()
                        .HasForeignKey("VendedorPadraoId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Lone.Domain.Entidades.ContaFornecedor", b =>
                {
                    b.HasOne("Lone.Domain.Entidades.Pessoa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Lone.Domain.Entidades.Pessoa", null)
                        .WithMany("ContasFornecedor")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lone.Domain.Entidades.Pessoa", null)
                        .WithMany()
                        .HasForeignKey("TransportadoraPadraoId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Lone.Domain.Entidades.Contato", b =>
                {
                    b.HasOne("Lone.Domain.Entidades.Pessoa", null)
                        .WithMany("Contatos")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lone.Domain.Entidades.Pessoa", null)
                        .WithMany()
                        .HasForeignKey("PessoaVinculadaId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Lone.Domain.Entidades.Estabelecimento", b =>
                {
                    b.HasOne("Lone.Domain.Entidades.PessoaEndereco", "EnderecoFiscal")
                        .WithMany()
                        .HasForeignKey("EnderecoFiscalId");

                    b.HasOne("Lone.Domain.Entidades.Pessoa", null)
                        .WithMany("Estabelecimentos")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnderecoFiscal");
                });

            modelBuilder.Entity("Lone.Domain.Entidades.MeioContato", b =>
                {
                    b.HasOne("Lone.Domain.Entidades.Pessoa", null)
                        .WithMany("MeiosContato")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lone.Domain.Entidades.PendenciaMunicipio", b =>
                {
                    b.HasOne("Lone.Domain.Entidades.Municipio", null)
                        .WithMany()
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Lone.Domain.Entidades.Pessoa", null)
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lone.Domain.Entidades.PerfilPermissao", b =>
                {
                    b.HasOne("Lone.Domain.Entidades.Perfil", null)
                        .WithMany("Permissoes")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lone.Domain.Entidades.Pessoa", b =>
                {
                    b.HasOne("Lone.Domain.Entidades.GrupoEconomico", null)
                        .WithMany()
                        .HasForeignKey("GrupoEconomicoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Lone.Domain.Entidades.Pessoa", null)
                        .WithMany()
                        .HasForeignKey("MescladaEmId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Lone.Domain.Entidades.Municipio", null)
                        .WithMany()
                        .HasForeignKey("NaturalidadeMunicipioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Lone.Domain.Entidades.PessoaConsentimento", b =>
                {
                    b.HasOne("Lone.Domain.Entidades.Pessoa", null)
                        .WithMany("Consentimentos")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lone.Domain.Entidades.PessoaDocumento", b =>
                {
                    b.HasOne("Lone.Domain.Entidades.Pessoa", null)
                        .WithMany("Documentos")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lone.Domain.Entidades.PessoaEndereco", b =>
                {
                    b.HasOne("Lone.Domain.Entidades.Municipio", null)
                        .WithMany()
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Lone.Domain.Entidades.Pessoa", null)
                        .WithMany("Enderecos")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lone.Domain.Entidades.PessoaEtiqueta", b =>
                {
                    b.HasOne("Lone.Domain.Entidades.Etiqueta", null)
                        .WithMany()
                        .HasForeignKey("EtiquetaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lone.Domain.Entidades.Pessoa", null)
                        .WithMany("Etiquetas")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lone.Domain.Entidades.PessoaPapel", b =>
                {
                    b.HasOne("Lone.Domain.Entidades.Pessoa", null)
                        .WithMany("Papeis")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lone.Domain.Entidades.PessoaRelacionamento", b =>
                {
                    b.HasOne("Lone.Domain.Entidades.Pessoa", null)
                        .WithMany()
                        .HasForeignKey("PessoaDestinoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Lone.Domain.Entidades.Pessoa", null)
                        .WithMany("Relacionamentos")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lone.Domain.Entidades.TipoRelacionamento", "TipoRelacionamento")
                        .WithMany()
                        .HasForeignKey("TipoRelacionamentoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TipoRelacionamento");
                });

            modelBuilder.Entity("Lone.Domain.Entidades.PessoaSocio", b =>
                {
                    b.HasOne("Lone.Domain.Entidades.Pessoa", null)
                        .WithMany("Socios")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lone.Domain.Entidades.PessoaValorPersonalizado", b =>
                {
                    b.HasOne("Lone.Domain.Entidades.CampoPersonalizado", null)
                        .WithMany()
                        .HasForeignKey("CampoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lone.Domain.Entidades.CampoPersonalizadoOpcao", null)
                        .WithMany()
                        .HasForeignKey("OpcaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Lone.Domain.Entidades.Pessoa", null)
                        .WithMany("ValoresPersonalizados")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lone.Domain.Entidades.TokenRenovacao", b =>
                {
                    b.HasOne("Lone.Domain.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lone.Domain.Entidades.UsuarioAcesso", b =>
                {
                    b.HasOne("Lone.Domain.Entidades.Usuario", null)
                        .WithOne("Acesso")
                        .HasForeignKey("Lone.Domain.Entidades.UsuarioAcesso", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lone.Domain.Entidades.UsuarioPerfil", b =>
                {
                    b.HasOne("Lone.Domain.Entidades.Pessoa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Lone.Domain.Entidades.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lone.Domain.Entidades.Usuario", null)
                        .WithMany("Perfis")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("Lone.Domain.Entidades.CampoPersonalizado", b =>
                {
                    b.Navigation("Opcoes");
                });

            modelBuilder.Entity("Lone.Domain.Entidades.Perfil", b =>
                {
                    b.Navigation("Permissoes");
                });

            modelBuilder.Entity("Lone.Domain.Entidades.Pessoa", b =>
                {
                    b.Navigation("Bloqueios");

                    b.Navigation("Consentimentos");

                    b.Navigation("ContasCliente");

                    b.Navigation("ContasFornecedor");

                    b.Navigation("Contatos");

                    b.Navigation("Documentos");

                    b.Navigation("Enderecos");

                    b.Navigation("Estabelecimentos");

                    b.Navigation("Etiquetas");

                    b.Navigation("MeiosContato");

                    b.Navigation("Papeis");

                    b.Navigation("Relacionamentos");

                    b.Navigation("Socios");

                    b.Navigation("ValoresPersonalizados");
                });

            modelBuilder.Entity("Lone.Domain.Entidades.Usuario", b =>
                {
                    b.Navigation("Acesso");

                    b.Navigation("Perfis");
                });
#pragma warning restore 612, 618
        }
    }
}
